import asyncio
import json
import logging
import uuid
from collections.abc import AsyncIterator
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from lib import agent_llm
from lib.agent_rules import rule_based_answer
from lib.datasets import CROPS, canonical_crop, load_datasets
from lib.db import db
from models.agent import AgentAnswer, AgentAskRequest, AgentHistoryResponse, AgentMessage
from routers.dashboard import validate_window

router = APIRouter(prefix="/agent", tags=["agent"])
logger = logging.getLogger(__name__)
HISTORY_LIMIT = 40


def now() -> datetime:
    return datetime.now(timezone.utc)


async def store_message(session_id: str | None, role: str, text: str, crop: str, answer: AgentAnswer | None = None) -> None:
    if not session_id:
        return
    document = AgentMessage(
        id=str(uuid.uuid4()), session_id=session_id, role=role, text=text, crop_name=crop, created_at=now(),
        evidence=answer.evidence if answer else [], chart=answer.chart if answer else [], mode=answer.mode if answer else None,
        code=answer.code if answer else None, result_preview=answer.result_preview if answer else None,
    ).model_dump()
    await db.agent_messages.insert_one(document)


def resolve(request: AgentAskRequest) -> tuple[str, str | None, str | None]:
    crop = canonical_crop(request.crop_name)
    if crop not in CROPS:
        crop = "Wheat"
    start, end = validate_window(request.date_from, request.date_to)
    return crop, start, end


async def llm_answer(request: AgentAskRequest, crop: str, start: str | None, end: str | None, on_token=None, on_stage=None) -> AgentAnswer:
    bundle = await load_datasets()
    session = request.session_id or "anonymous"
    if on_stage:
        await on_stage("planning", None)
    plan, result = await agent_llm.plan_and_execute(request.query, crop, session, bundle, start, end)
    result_text, rows = agent_llm.preview(result)
    if on_stage:
        await on_stage("executed", {"code": plan["code"], "approach": plan.get("approach", ""), "rows": rows, "preview": result_text})
    chunks: list[str] = []
    async for token in agent_llm.stream_explanation(request.query, plan["code"], result_text, rows, session):
        chunks.append(token)
        if on_token:
            await on_token(token)
    text = "".join(chunks).strip() or "The query ran but produced no explanation."
    evidence = [
        f"{rows} result row{'s' if rows != 1 else ''} · pandas query generated by {agent_llm.MODEL_NAME}",
        f"Window: {start or bundle.arrivals['date'].min():%Y-%m-%d} → {end or bundle.arrivals['date'].max():%Y-%m-%d}" if isinstance(start, str) or isinstance(end, str) else f"Full cleaned window · {bundle.source}",
        "Source: mandi_master, mandi_arrivals, price_and_msp, transport, weather (cleaned)",
    ]
    return AgentAnswer(
        answer=text, intent="llm-analysis", source=bundle.source, grounded_at=bundle.fetched_at, evidence=evidence,
        chart=agent_llm.chart_points(result, plan.get("chart")), mode="llm", code=plan["code"], result_preview=result_text[:4000],
    )


@router.post("/ask", response_model=AgentAnswer)
async def ask_agent(request: AgentAskRequest) -> AgentAnswer:
    crop, start, end = resolve(request)
    await store_message(request.session_id, "user", request.query, crop)
    answer: AgentAnswer | None = None
    if agent_llm.llm_enabled():
        try:
            answer = await llm_answer(request, crop, start, end)
        except Exception as exc:  # noqa: BLE001 - any LLM/sandbox failure degrades to the rule-based agent
            logger.warning("LLM agent failed, falling back to rules: %s", exc)
    if answer is None:
        bundle = await load_datasets()
        answer = rule_based_answer(bundle, request.query, crop, start, end)
    await store_message(request.session_id, "agent", answer.answer, crop, answer)
    return answer


@router.post("/ask/stream")
async def ask_agent_stream(request: AgentAskRequest) -> StreamingResponse:
    crop, start, end = resolve(request)

    async def events() -> AsyncIterator[str]:
        queue: asyncio.Queue[str | None] = asyncio.Queue()

        def emit(payload: dict) -> None:
            queue.put_nowait(f"data: {json.dumps(payload, default=str)}\n\n")

        async def on_token(token: str) -> None:
            emit({"event": "token", "text": token})

        async def on_stage(stage: str, extra: dict | None) -> None:
            emit({"event": "stage", "stage": stage, **(extra or {})})

        async def worker() -> None:
            await store_message(request.session_id, "user", request.query, crop)
            answer: AgentAnswer | None = None
            if agent_llm.llm_enabled():
                try:
                    answer = await llm_answer(request, crop, start, end, on_token=on_token, on_stage=on_stage)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("LLM agent stream failed, falling back to rules: %s", exc)
                    emit({"event": "stage", "stage": "fallback", "reason": str(exc)[:200]})
            if answer is None:
                bundle = await load_datasets()
                answer = rule_based_answer(bundle, request.query, crop, start, end)
            await store_message(request.session_id, "agent", answer.answer, crop, answer)
            emit({"event": "done", "answer": answer.model_dump(mode="json")})
            queue.put_nowait(None)

        task = asyncio.create_task(worker())
        try:
            while True:
                try:
                    item = await asyncio.wait_for(queue.get(), timeout=15)
                except asyncio.TimeoutError:
                    yield ": keep-alive\n\n"
                    continue
                if item is None:
                    break
                yield item
        finally:
            if not task.done():
                task.cancel()

    return StreamingResponse(events(), media_type="text/event-stream", headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@router.get("/history/{session_id}", response_model=AgentHistoryResponse)
async def get_history(session_id: str) -> AgentHistoryResponse:
    if not session_id or len(session_id) > 64:
        raise HTTPException(status_code=422, detail="Invalid session id")
    documents = await db.agent_messages.find({"session_id": session_id}, {"_id": 0}).sort("created_at", -1).limit(HISTORY_LIMIT).to_list(HISTORY_LIMIT)
    return AgentHistoryResponse(session_id=session_id, messages=[AgentMessage(**document) for document in reversed(documents)])
