import { useMemo } from "react";
import { Layers3, Maximize2, Navigation, Radio, Route, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CropName, MandiRow, WarehousePerformance } from "@/data/types";

interface AgriOrbitCentralVisualProps { crop: CropName; rows: MandiRow[]; totalHubs: number; warehouses: WarehousePerformance[]; selectedMandiId: string; onSelectMandi: (id: string) => void; }

const WAREHOUSE_SLOTS = [{ x: 118, y: 92 }, { x: 782, y: 92 }, { x: 118, y: 260 }, { x: 782, y: 260 }, { x: 118, y: 428 }, { x: 782, y: 428 }];

export function AgriOrbitCentralVisual({ crop, rows, totalHubs, warehouses, selectedMandiId, onSelectMandi }: AgriOrbitCentralVisualProps) {
  const selected = rows.find((row) => row.mandi_id === selectedMandiId) ?? rows[0];
  const warehousePoints = useMemo(() => warehouses.slice(0, WAREHOUSE_SLOTS.length).map((item, index) => ({ ...item, ...WAREHOUSE_SLOTS[index] })), [warehouses]);
  const routes = useMemo(() => rows.slice(0, 8), [rows]);
  const toXY = (row: MandiRow) => ({ x: 130 + (row.position_x / 100) * 640, y: 60 + (row.position_y / 100) * 400 });
  const warehouseFor = (name: string) => warehousePoints.find((item) => item.destination_warehouse === name);
  return <article className="relative min-h-[430px] overflow-hidden rounded-3xl border border-[#69C7F5]/15 bg-[#0B192C] shadow-[0_25px_80px_rgba(0,0,0,0.22)]" data-testid="agri-orbit-card">
    <div className="absolute inset-0 opacity-80" style={{ background: "radial-gradient(circle at 55% 47%, rgba(180,146,64,.19), transparent 26%), radial-gradient(circle at 20% 10%, rgba(101,140,73,.17), transparent 30%)" }} />
    <div className="absolute left-5 top-5 z-10"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-xl border border-[#A5F36B]/25 bg-[#A5F36B]/10 text-[#A5F36B]"><Navigation className="size-4" /></div><div><p className="text-sm font-medium text-white" data-testid="agri-orbit-title">Agri-Orbit network</p><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-[#69C7F5]" data-testid="agri-orbit-subtitle">{rows.length} of {totalHubs} hubs · {warehouses.length} destinations · live</p></div></div></div>
    <div className="absolute right-4 top-4 z-10 flex gap-2"><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] bg-[#07111F]/70 text-[#8CA0B5] hover:text-[#A5F36B]" data-testid="agri-orbit-layer-button" aria-label="Toggle map layers"><Layers3 className="size-4" /></Button><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] bg-[#07111F]/70 text-[#8CA0B5] hover:text-[#A5F36B]" data-testid="agri-orbit-expand-button" aria-label="Expand orbit view"><Maximize2 className="size-4" /></Button></div>
    <svg viewBox="0 0 900 520" className="relative z-[1] h-full min-h-[430px] w-full" role="img" aria-label={`Interactive mandi network for ${crop}`} data-testid="agri-orbit-svg-container">
      <defs><filter id="softGlow"><feGaussianBlur stdDeviation="4" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><linearGradient id="routeGreen" x1="0" x2="1"><stop stopColor="#B9C27B" stopOpacity="0.08" /><stop offset="0.5" stopColor="#E0A13B" stopOpacity="0.85" /><stop offset="1" stopColor="#A5F36B" stopOpacity="0.15" /></linearGradient><radialGradient id="orbitFill"><stop stopColor="#A3B56C" stopOpacity="0.16" /><stop offset="1" stopColor="#65D68A" stopOpacity="0" /></radialGradient><clipPath id="landscapeClip"><circle cx="450" cy="270" r="153" /></clipPath></defs>
      <circle cx="450" cy="270" r="188" fill="url(#orbitFill)" /><image href="https://images.unsplash.com/photo-1511802269876-bf873cc7b2c5?crop=entropy&cs=srgb&fm=jpg&q=80" x="297" y="117" width="306" height="306" preserveAspectRatio="xMidYMid slice" clipPath="url(#landscapeClip)" opacity=".5" /><circle cx="450" cy="270" r="153" fill="#182418" fillOpacity=".35" /><circle cx="450" cy="270" r="190" fill="none" stroke="#A0A56B" strokeOpacity="0.3" strokeDasharray="3 12" /><circle cx="450" cy="270" r="170" fill="none" stroke="#D79B3B" strokeOpacity="0.35" strokeDasharray="56 18 3 20" /><circle cx="450" cy="270" r="136" fill="none" stroke="#A5F36B" strokeOpacity="0.28" strokeDasharray="2 10" /><circle cx="450" cy="270" r="80" fill="none" stroke="#F4C86B" strokeOpacity="0.24" strokeDasharray="1 8" />
      <text x="450" y="500" textAnchor="middle" fill="#F4C86B" fontSize="10" fontFamily="monospace" letterSpacing="2" opacity=".7">PUNJAB · HARYANA · UTTAR PRADESH</text>
      {routes.map((row) => { const from = toXY(row); const to = warehouseFor(row.destination_warehouse); if (!to) return null; return <path key={`route-${row.mandi_id}`} d={`M ${from.x} ${from.y} Q ${(from.x + to.x) / 2} ${(from.y + to.y) / 2 - 40} ${to.x} ${to.y}`} fill="none" stroke="url(#routeGreen)" strokeWidth={row.mandi_id === selectedMandiId ? 2.5 : 1.1} strokeDasharray="5 7" className="orbit-route" data-testid={`agri-orbit-route-${row.mandi_id.toLowerCase()}`} />; })}
      {warehousePoints.map((warehouse) => <g key={warehouse.destination_warehouse} data-testid={`agri-orbit-warehouse-${warehouse.destination_warehouse.toLowerCase()}`}><circle cx={warehouse.x} cy={warehouse.y} r="11" fill="#69C7F5" fillOpacity={selected?.destination_warehouse === warehouse.destination_warehouse ? ".3" : ".1"} stroke="#69C7F5" strokeOpacity=".45" /><Warehouse x={warehouse.x - 7} y={warehouse.y - 7} width="14" height="14" stroke="#69C7F5" /><text x={warehouse.x} y={warehouse.y + 26} textAnchor="middle" fill="#8CA0B5" fontSize="8" fontFamily="monospace">{warehouse.destination_warehouse}</text><text x={warehouse.x} y={warehouse.y + 37} textAnchor="middle" fill="#5B738B" fontSize="7" fontFamily="monospace">{warehouse.transit_hours.toFixed(1)}h · {warehouse.trips} trips</text></g>)}
      {rows.map((row) => { const color = row.risk === "high" ? "#FF8585" : row.risk === "medium" ? "#F4C86B" : "#A5F36B"; const { x, y } = toXY(row); const selectedNode = row.mandi_id === selectedMandiId; return <g key={row.mandi_id} onClick={() => onSelectMandi(row.mandi_id)} className="cursor-pointer" data-testid={`agri-orbit-pin-${row.mandi_id.toLowerCase()}`} role="button" tabIndex={0} aria-label={`Select ${row.mandi_name}`}><title>{`${row.mandi_name} · ${row.state} · ₹${row.modal_price.toLocaleString("en-IN")} modal · ${row.risk} risk`}</title><circle cx={x} cy={y} r={selectedNode ? 20 : 10} fill={color} fillOpacity=".09" stroke={color} strokeOpacity={selectedNode ? ".7" : ".25"} className={selectedNode ? "orbit-pulse" : ""} /><circle cx={x} cy={y} r={selectedNode ? 6 : 3.5} fill={color} filter="url(#softGlow)" />{selectedNode && <text x={x + 12} y={y + 3} fill="#FFFFFF" fontSize="10" fontFamily="monospace">{row.mandi_id.replace("MANDI", "M")} · {row.mandi_name}</text>}</g>; })}
    </svg>
    <div className="absolute bottom-4 left-5 right-5 z-10 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-[#07111F]/70 px-3 py-2 backdrop-blur-md" data-testid="agri-orbit-legend"><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#A5F36B]" /> Stable</span><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#F4C86B]" /> Watch</span><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#FF8585]" /> Risk</span></div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#5B738B]" data-testid="agri-orbit-selected-route"><Route className="size-3 text-[#69C7F5]" /> {selected ? `${selected.mandi_id} → ${selected.destination_warehouse} · ${selected.transit_hours.toFixed(1)}h avg` : "No hub in filter"}</div></div>
    <div className="absolute right-5 top-20 z-10 hidden rounded-xl border border-[#69C7F5]/15 bg-[#07111F]/80 px-3 py-2 backdrop-blur-md sm:block" data-testid="agri-orbit-mode-info"><div className="flex items-center gap-2 text-[10px] text-[#69C7F5]"><Radio className="size-3" /> Orbit mode <span className="text-white">· {crop}</span></div><div className="mt-1 text-[9px] text-[#5B738B]">Pins placed by district · click a hub to inspect</div></div>
    {rows.length === 0 && <div className="absolute inset-0 z-10 flex items-center justify-center bg-[#07111F]/50 text-xs text-[#8CA0B5]" data-testid="agri-orbit-empty-state">No mandis match the current filters</div>}
  </article>;
}
