import { useMemo } from "react";
import { Crosshair, Layers3, Maximize2, Navigation, Radio, Route, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CropName, MandiRow } from "@/data/mockData";

interface AgriOrbitCentralVisualProps { crop: CropName; rows: MandiRow[]; selectedMandiId: string; onSelectMandi: (id: string) => void; }

export function AgriOrbitCentralVisual({ crop, rows, selectedMandiId, onSelectMandi }: AgriOrbitCentralVisualProps) {
  const selected = rows.find((row) => row.mandi_id === selectedMandiId) ?? rows[0];
  const routes = useMemo(() => rows.slice(0, 5), [rows]);
  return <article className="relative min-h-[430px] overflow-hidden rounded-3xl border border-[#69C7F5]/15 bg-[#0B192C] shadow-[0_25px_80px_rgba(0,0,0,0.22)]" data-testid="agri-orbit-card">
    <div className="absolute inset-0 opacity-80" style={{ background: "radial-gradient(circle at 55% 47%, rgba(101,214,138,.13), transparent 26%), radial-gradient(circle at 20% 10%, rgba(105,199,245,.08), transparent 30%)" }} />
    <div className="absolute left-5 top-5 z-10"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-xl border border-[#A5F36B]/25 bg-[#A5F36B]/10 text-[#A5F36B]"><Navigation className="size-4" /></div><div><p className="text-sm font-medium text-white" data-testid="agri-orbit-title">Agri-Orbit network</p><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-[#69C7F5]" data-testid="agri-orbit-subtitle">57 hubs · 06 routes · live</p></div></div></div>
    <div className="absolute right-4 top-4 z-10 flex gap-2"><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] bg-[#07111F]/70 text-[#8CA0B5] hover:text-[#A5F36B]" data-testid="agri-orbit-layer-button" aria-label="Toggle map layers"><Layers3 className="size-4" /></Button><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] bg-[#07111F]/70 text-[#8CA0B5] hover:text-[#A5F36B]" data-testid="agri-orbit-expand-button" aria-label="Expand orbit view"><Maximize2 className="size-4" /></Button></div>
    <svg viewBox="0 0 900 520" className="relative z-[1] h-full min-h-[430px] w-full" role="img" aria-label={`Interactive mandi network for ${crop}`} data-testid="agri-orbit-svg-container">
      <defs><filter id="softGlow"><feGaussianBlur stdDeviation="4" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><linearGradient id="routeGreen" x1="0" x2="1"><stop stopColor="#A5F36B" stopOpacity="0.1" /><stop offset="0.5" stopColor="#A5F36B" stopOpacity="0.85" /><stop offset="1" stopColor="#69C7F5" stopOpacity="0.2" /></linearGradient><radialGradient id="orbitFill"><stop stopColor="#65D68A" stopOpacity="0.1" /><stop offset="1" stopColor="#65D68A" stopOpacity="0" /></radialGradient></defs>
      <circle cx="450" cy="270" r="188" fill="url(#orbitFill)" /><circle cx="450" cy="270" r="190" fill="none" stroke="#69C7F5" strokeOpacity="0.14" strokeDasharray="3 12" /><circle cx="450" cy="270" r="136" fill="none" stroke="#A5F36B" strokeOpacity="0.17" strokeDasharray="2 10" /><circle cx="450" cy="270" r="80" fill="none" stroke="#F4C86B" strokeOpacity="0.15" strokeDasharray="1 8" /><circle cx="450" cy="270" r="32" fill="#A5F36B" fillOpacity="0.06" stroke="#A5F36B" strokeOpacity="0.35" /><text x="450" y="266" textAnchor="middle" fill="#A5F36B" fontSize="11" fontFamily="monospace" letterSpacing="2">INDIA</text><text x="450" y="284" textAnchor="middle" fill="#8CA0B5" fontSize="9" fontFamily="monospace">SUPPLY CORE</text>
      {routes.map((row, index) => <path key={row.mandi_id} d={`M ${row.position.x * 9} ${row.position.y * 5.2} Q ${450 + (index % 2 ? 100 : -100)} ${210 + index * 18} ${index % 2 ? 688 : 272} ${395 - index * 28}`} fill="none" stroke="url(#routeGreen)" strokeWidth={row.mandi_id === selectedMandiId ? 2.5 : 1.1} strokeDasharray="5 7" className="orbit-route" />)}
      {[{ x: 272, y: 395, label: "WH-NORTH" }, { x: 688, y: 367, label: "WH-CENTRAL" }, { x: 272, y: 339, label: "WH-WEST" }].map((warehouse) => <g key={warehouse.label}><circle cx={warehouse.x} cy={warehouse.y} r="11" fill="#69C7F5" fillOpacity=".1" stroke="#69C7F5" strokeOpacity=".45" /><Warehouse x={warehouse.x - 7} y={warehouse.y - 7} width="14" height="14" stroke="#69C7F5" /><text x={warehouse.x} y={warehouse.y + 28} textAnchor="middle" fill="#5B738B" fontSize="8" fontFamily="monospace">{warehouse.label}</text></g>)}
      {rows.map((row) => { const color = row.risk === "high" ? "#FF8585" : row.risk === "medium" ? "#F4C86B" : "#A5F36B"; const x = row.position.x * 9; const y = row.position.y * 5.2; const selectedNode = row.mandi_id === selectedMandiId; return <g key={row.mandi_id} onClick={() => onSelectMandi(row.mandi_id)} className="cursor-pointer" data-testid={`agri-orbit-pin-${row.mandi_id.toLowerCase()}`} role="button" tabIndex={0} aria-label={`Select ${row.mandi_name}`}><circle cx={x} cy={y} r={selectedNode ? 22 : 14} fill={color} fillOpacity=".09" stroke={color} strokeOpacity={selectedNode ? ".7" : ".25"} className={selectedNode ? "orbit-pulse" : ""} /><circle cx={x} cy={y} r={selectedNode ? 7 : 5} fill={color} filter="url(#softGlow)" /><text x={x + 13} y={y + 3} fill={selectedNode ? "#FFFFFF" : "#8CA0B5"} fontSize={selectedNode ? "10" : "8"} fontFamily="monospace">{row.mandi_id.replace("MANDI", "M")}</text></g>; })}
    </svg>
    <div className="absolute bottom-4 left-5 right-5 z-10 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-[#07111F]/70 px-3 py-2 backdrop-blur-md" data-testid="agri-orbit-legend"><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#A5F36B]" /> Stable</span><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#F4C86B]" /> Watch</span><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><span className="size-1.5 rounded-full bg-[#FF8585]" /> Risk</span></div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#5B738B]" data-testid="agri-orbit-selected-route"><Route className="size-3 text-[#69C7F5]" /> {selected?.destinationWarehouse} · {selected?.transitHours}h avg</div></div>
    <div className="absolute right-5 top-20 z-10 hidden rounded-xl border border-[#69C7F5]/15 bg-[#07111F]/80 px-3 py-2 backdrop-blur-md sm:block" data-testid="agri-orbit-mode-info"><div className="flex items-center gap-2 text-[10px] text-[#69C7F5]"><Radio className="size-3" /> Orbit mode <span className="text-white">· {crop}</span></div><div className="mt-1 text-[9px] text-[#5B738B]">Click a hub to inspect its signal</div></div>
  </article>;
}
