import { ArrowUpRight, CloudRain, LineChart as LineChartIcon, Package, Route, TrendingDown, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "@/lib/recharts";
import type { CropName, CropProfileMap } from "@/data/mockData";
import { cropProfiles, getMandiRows, getPriceTrend, warehousePerformance, weatherSeries } from "@/data/mockData";

const tooltipStyle = { backgroundColor: "#0B192C", border: "1px solid rgba(105,199,245,.18)", borderRadius: "12px", color: "#fff", fontSize: 11 };

interface AnalyticsChartsProps { crop: CropName; profiles?: CropProfileMap; }

export function AnalyticsCharts({ crop, profiles = cropProfiles }: AnalyticsChartsProps) {
  const profile = profiles[crop];
  const trend = getPriceTrend(crop, profiles);
  const rows = getMandiRows(crop, profiles).slice(0, 6);
  return <section className="grid grid-cols-1 gap-6 lg:grid-cols-2" data-testid="analytics-grid">
    <article className="rounded-3xl border border-white/[0.07] bg-[#102235]/60 p-5 sm:p-6" data-testid="price-msp-chart-container"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#69C7F5]">Market benchmark</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white" data-testid="price-msp-chart-title">Modal price vs MSP</h3></div><div className="flex gap-3 text-[10px] text-[#8CA0B5]" data-testid="price-msp-chart-legend"><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-[#A5F36B]" /> Modal</span><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-[#F4C86B]" /> MSP</span></div></div><div className="h-60" data-testid="price-msp-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{ top: 5, right: 0, left: -18, bottom: 0 }} barGap={4}><CartesianGrid stroke="rgba(140,160,181,.08)" vertical={false} /><XAxis dataKey="mandi_id" tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value: number) => `₹${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgba(105,199,245,.04)" }} formatter={(value: number, name: string) => [`₹${value.toLocaleString("en-IN")}`, name === "modalPrice" ? "Modal price" : "MSP"]} /><Bar dataKey="modalPrice" fill="#A5F36B" radius={[4, 4, 0, 0]} barSize={11} /><Bar dataKey="msp" fill="#F4C86B" radius={[4, 4, 0, 0]} barSize={11} /></BarChart></ResponsiveContainer></div><div className="mt-4 flex items-center gap-2 border-t border-white/[0.06] pt-3 text-[10px] text-[#8CA0B5]" data-testid="price-msp-chart-note"><ArrowUpRight className="size-3 text-[#A5F36B]" /> {crop} is tracking <span className="text-[#A5F36B]">₹{Math.abs(profile.modal - profile.msp)} {profile.modal >= profile.msp ? "above" : "below"} floor</span> at blended average</div></article>

    <article className="rounded-3xl border border-white/[0.07] bg-[#102235]/60 p-5 sm:p-6" data-testid="price-trend-chart-container"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#A5F36B]">Signal movement</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white" data-testid="price-trend-chart-title">Price trend <span className="ml-2 text-xs font-normal text-[#A5F36B]">{profile.trend > 0 ? "↗" : "↘"} {Math.abs(profile.trend)}%</span></h3></div><div className="flex items-center gap-1 rounded-lg border border-white/[0.08] p-1" data-testid="price-trend-range-control"><button className="rounded-md bg-white/[0.08] px-2 py-1 text-[9px] text-white" data-testid="price-trend-weekly-button">W</button><button className="px-2 py-1 text-[9px] text-[#5B738B]" data-testid="price-trend-monthly-button">M</button></div></div><div className="h-60" data-testid="price-trend-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend} margin={{ top: 5, right: 0, left: -18, bottom: 0 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#A5F36B" stopOpacity=".22" /><stop offset="100%" stopColor="#A5F36B" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="rgba(140,160,181,.08)" vertical={false} /><XAxis dataKey="date" tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value: number) => `₹${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number, name: string) => [`₹${value.toLocaleString("en-IN")}`, name === "modal" ? "Modal price" : "MSP"]} /><ReferenceLine y={profile.msp} stroke="#F4C86B" strokeDasharray="4 4" strokeOpacity={.55} /><Area type="monotone" dataKey="modal" stroke="#A5F36B" fill="url(#trendFill)" strokeWidth={2} dot={{ fill: "#A5F36B", r: 2 }} /><Line type="monotone" dataKey="msp" stroke="#F4C86B" strokeDasharray="4 4" strokeWidth={1.5} dot={false} /></ComposedChart></ResponsiveContainer></div><div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3 text-[10px] text-[#8CA0B5]"><span className="flex items-center gap-2"><LineChartIcon className="size-3 text-[#A5F36B]" /> Daily cleaned signal</span><span data-testid="price-trend-last-price">Latest ₹{trend[trend.length - 1].modal.toLocaleString("en-IN")}</span></div></article>

    <article className="rounded-3xl border border-white/[0.07] bg-[#102235]/60 p-5 sm:p-6" data-testid="logistics-transit-chart"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#69C7F5]">Route health</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white">Warehouse transit matrix</h3></div><span className="flex items-center gap-1.5 rounded-full bg-[#69C7F5]/10 px-2.5 py-1 text-[10px] text-[#69C7F5]"><Route className="size-3" /> {profile.transit}h avg</span></div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={warehousePerformance} layout="vertical" margin={{ top: 0, right: 8, left: 8, bottom: 0 }}><CartesianGrid stroke="rgba(140,160,181,.08)" horizontal={false} /><XAxis type="number" domain={[0, 16]} tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="warehouse" width={76} tick={{ fill: "#8CA0B5", fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`${value} hrs`, "Transit"]} /><Bar dataKey="hours" fill="#69C7F5" radius={[0, 5, 5, 0]} barSize={16} /></BarChart></ResponsiveContainer></div><div className="mt-4 grid grid-cols-3 gap-2 border-t border-white/[0.06] pt-3" data-testid="logistics-insight-stats"><div><p className="text-[9px] text-[#5B738B]">Fastest</p><p className="mt-1 text-xs text-white">WH-SOUTH</p></div><div><p className="text-[9px] text-[#5B738B]">Delay rate</p><p className="mt-1 text-xs text-[#A5F36B]">{profile.delay}%</p></div><div><p className="text-[9px] text-[#5B738B]">Trips parsed</p><p className="mt-1 text-xs text-white">10,400</p></div></div></article>

    <article className="rounded-3xl border border-white/[0.07] bg-[#102235]/60 p-5 sm:p-6" data-testid="weather-correlation-chart"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#69C7F5]">Weather impact</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white">Rainfall ↔ arrivals</h3></div><div className="text-right"><p className="font-mono text-2xl font-bold text-[#69C7F5]">0.54</p><p className="text-[9px] uppercase tracking-wider text-[#5B738B]">correlation</p></div></div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={weatherSeries} margin={{ top: 5, right: 0, left: -18, bottom: 0 }}><defs><linearGradient id="rainFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#69C7F5" stopOpacity=".26" /><stop offset="100%" stopColor="#69C7F5" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="rgba(140,160,181,.08)" vertical={false} /><XAxis dataKey="date" tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis yAxisId="left" tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis yAxisId="right" orientation="right" tick={{ fill: "#5B738B", fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number, name: string) => [name === "rainfall" ? `${value} mm` : `${value}°C`, name === "rainfall" ? "Rainfall" : "Temperature"]} /><Area yAxisId="left" type="monotone" dataKey="rainfall" stroke="#69C7F5" fill="url(#rainFill)" strokeWidth={2} /><Line yAxisId="right" type="monotone" dataKey="temperature" stroke="#F4C86B" strokeWidth={2} dot={false} /></AreaChart></ResponsiveContainer></div><div className="mt-4 flex items-center gap-2 border-t border-white/[0.06] pt-3 text-[10px] text-[#8CA0B5]"><CloudRain className="size-3 text-[#69C7F5]" /> Sensor readings converted to IST · units normalized</div></article>

    <article className="rounded-3xl border border-white/[0.07] bg-[#102235]/60 p-5 sm:p-6 lg:col-span-2" data-testid="below-msp-distribution-card"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#FF8585]">Risk distribution</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white">Above vs. below MSP by crop</h3></div><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><Package className="size-3" /> 12,000 price records</span></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8" data-testid="below-msp-crop-grid">{Object.entries(profiles).map(([name, item]) => <div key={name} className="flex items-center gap-3 rounded-xl border border-white/[0.06] bg-[#07111F]/40 p-3" data-testid={`below-msp-crop-${name.toLowerCase()}`}><div className="relative size-10 shrink-0"><svg viewBox="0 0 40 40" className="size-10 -rotate-90"><circle cx="20" cy="20" r="15" fill="none" stroke="#A5F36B" strokeWidth="5" strokeDasharray={`${(100 - item.belowMsp) * 0.942} 100`} /><circle cx="20" cy="20" r="15" fill="none" stroke="#FF8585" strokeWidth="5" strokeDasharray={`${item.belowMsp * 0.942} 100`} strokeDashoffset={`${-(100 - item.belowMsp) * 0.942}`} /></svg><span className="absolute inset-0 flex items-center justify-center text-[9px] font-bold text-white">{item.belowMsp.toFixed(0)}%</span></div><div className="min-w-0"><p className="truncate text-xs font-medium text-white">{name}</p><p className="mt-1 flex items-center gap-1 text-[9px] text-[#FF8585]"><TrendingDown className="size-3" /> below floor</p></div></div>)}</div></article>
  </section>;
}
