import { ArrowUpRight, CloudSun, MapPin, ThermometerSun, Wheat } from "lucide-react";
import type { CropName, MandiRow } from "@/data/mockData";
import { cropProfiles } from "@/data/mockData";

interface HeroLandscapeCardProps { crop: CropName; selected: MandiRow; }

export function HeroLandscapeCard({ crop, selected }: HeroLandscapeCardProps) {
  const profile = cropProfiles[crop];
  return <article className="relative min-h-[430px] overflow-hidden rounded-3xl border border-[#F4C86B]/15 bg-[#102235]" data-testid="hero-landscape-card">
    <img src="https://images.unsplash.com/photo-1511802269876-bf873cc7b2c5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzR8MHwxfHNlYXJjaHwzfHxhZXJpYWwlMjBhZ3JpY3VsdHVyZSUyMGZpZWxkcyUyMGRyb25lJTIwbGFuZHNjYXBlJTIwZGFyayUyMGdyZWVufGVufDB8fHxncmVlbnwxNzg5MjE1Mjg1fDA&ixlib=rb-4.1.0&q=85" alt="Aerial agricultural fields" className="absolute inset-0 size-full object-cover opacity-75" data-testid="hero-landscape-image" />
    <div className="absolute inset-0 bg-gradient-to-t from-[#172018] via-[#172018]/55 to-[#172018]/10" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_40%_25%,rgba(226,176,66,.22),transparent_35%)]" />
    <div className="relative flex min-h-[430px] flex-col justify-between p-5 sm:p-6"><div className="flex items-start justify-between"><div className="flex items-center gap-2 rounded-full border border-white/15 bg-[#07111F]/50 px-3 py-1.5 text-[10px] text-[#E2E8F0] backdrop-blur-md" data-testid="hero-sensor-badge"><CloudSun className="size-3.5 text-[#F4C86B]" /> Field telemetry active</div><div className="rounded-full border border-[#A5F36B]/20 bg-[#07111F]/45 px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.14em] text-[#A5F36B]" data-testid="hero-data-label">Cleaned baseline</div></div>
      <div><div className="mb-4 flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-[#B8F7A1]" data-testid="hero-crop-label"><Wheat className="size-3.5" /> {crop} intelligence</div><h2 className="max-w-md text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl" data-testid="hero-landscape-title">Harvest signals,<br /><span className="text-[#A5F36B]">mapped to action.</span></h2><p className="mt-3 max-w-sm text-xs leading-relaxed text-[#D7E0E7]" data-testid="hero-landscape-description">{profile.outlook}. AgentIQ is tracking arrival pressure, price floors, and route health across the network.</p>
        <div className="mt-5 flex flex-wrap gap-2" data-testid="hero-insight-metrics"><div className="rounded-xl border border-white/10 bg-[#07111F]/55 px-3 py-2 backdrop-blur-sm"><p className="text-[9px] uppercase tracking-wider text-[#8CA0B5]">Season</p><p className="mt-1 text-xs text-white">{profile.season}</p></div><div className="rounded-xl border border-white/10 bg-[#07111F]/55 px-3 py-2 backdrop-blur-sm"><p className="text-[9px] uppercase tracking-wider text-[#8CA0B5]">Rainfall link</p><p className="mt-1 text-xs text-[#A5F36B]">0.54 correlation</p></div></div>
      </div></div>
    <div className="absolute bottom-5 right-5 w-[calc(100%-2.5rem)] max-w-[245px] rounded-2xl border border-[#F4C86B]/25 bg-[#07111F]/80 p-4 shadow-[0_14px_45px_rgba(0,0,0,0.3)] backdrop-blur-xl sm:right-6" data-testid="selected-mandi-panel"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex size-7 items-center justify-center rounded-lg bg-[#F4C86B]/10 text-[#F4C86B]"><MapPin className="size-3.5" /></span><div><p className="text-[10px] text-[#8CA0B5]">Selected hub</p><p className="text-xs font-medium text-white">{selected.mandi_name}</p></div></div><ArrowUpRight className="size-3.5 text-[#A5F36B]" /></div><div className="grid grid-cols-2 gap-3 border-t border-white/[0.08] pt-3"><div><p className="font-mono text-[9px] uppercase tracking-wider text-[#5B738B]">Modal / MSP</p><p className="mt-1 text-sm font-semibold text-white">₹{selected.modalPrice.toLocaleString("en-IN")}</p><p className="text-[10px] text-[#F4C86B]">₹{selected.msp.toLocaleString("en-IN")} floor</p></div><div><p className="font-mono text-[9px] uppercase tracking-wider text-[#5B738B]">Arrivals</p><p className="mt-1 text-sm font-semibold text-white">{(selected.arrivalQuantity / 1000).toFixed(1)}k</p><p className="flex items-center gap-1 text-[10px] text-[#69C7F5]"><ThermometerSun className="size-3" /> {selected.weather.split("·")[0]}</p></div></div></div>
  </article>;
}
