import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, ChevronLeft, ChevronRight, CloudSun, ExternalLink, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { MandiRow, RiskLevel } from "@/data/types";
import { formatInr, formatQtl } from "@/data/types";

interface MandiDataTableProps { rows: MandiRow[]; totalCount: number; search: string; onSearchChange: (value: string) => void; selectedMandiId: string; onSelectMandi: (id: string) => void; }

type SortKey = "mandi_name" | "state" | "modal_price" | "price_gap" | "arrival_quantity_qtl" | "transit_hours" | "risk";
const PAGE_SIZE = 10;
const RISK_ORDER: Record<RiskLevel, number> = { low: 0, medium: 1, high: 2 };
const COLUMNS: { key: SortKey | null; label: string }[] = [
  { key: "mandi_name", label: "Mandi" }, { key: "state", label: "State" }, { key: "modal_price", label: "Modal / MSP" }, { key: "price_gap", label: "Price gap" },
  { key: "arrival_quantity_qtl", label: "Arrivals" }, { key: "transit_hours", label: "Transit" }, { key: null, label: "Weather" }, { key: "risk", label: "Risk" }, { key: null, label: "" },
];

export function MandiDataTable({ rows, totalCount, search, onSearchChange, selectedMandiId, onSelectMandi }: MandiDataTableProps) {
  const [sortKey, setSortKey] = useState<SortKey>("arrival_quantity_qtl");
  const [direction, setDirection] = useState<"asc" | "desc">("desc");
  const [page, setPage] = useState(0);
  const visibleRows = useMemo(() => {
    const filtered = rows.filter((row) => `${row.mandi_name} ${row.state} ${row.district} ${row.mandi_id}`.toLowerCase().includes(search.toLowerCase()));
    const sorted = [...filtered].sort((left, right) => {
      const compare = sortKey === "risk" ? RISK_ORDER[left.risk] - RISK_ORDER[right.risk] : typeof left[sortKey] === "string" ? String(left[sortKey]).localeCompare(String(right[sortKey])) : Number(left[sortKey]) - Number(right[sortKey]);
      return direction === "asc" ? compare : -compare;
    });
    return sorted;
  }, [direction, rows, search, sortKey]);
  const pageCount = Math.max(1, Math.ceil(visibleRows.length / PAGE_SIZE));
  useEffect(() => { if (page > pageCount - 1) setPage(0); }, [page, pageCount]);
  const pageRows = visibleRows.slice(page * PAGE_SIZE, page * PAGE_SIZE + PAGE_SIZE);
  const toggleSort = (key: SortKey) => { if (key === sortKey) setDirection((current) => (current === "asc" ? "desc" : "asc")); else { setSortKey(key); setDirection(key === "mandi_name" || key === "state" ? "asc" : "desc"); } setPage(0); };
  const riskStyle: Record<RiskLevel, string> = { low: "border-[#A5F36B]/20 bg-[#A5F36B]/10 text-[#A5F36B]", medium: "border-[#F4C86B]/20 bg-[#F4C86B]/10 text-[#F4C86B]", high: "border-[#FF8585]/20 bg-[#FF8585]/10 text-[#FF8585]" };
  return <section className="rounded-3xl border border-white/[0.07] bg-[#102235]/60" data-testid="mandi-data-table"><div className="flex flex-col gap-4 border-b border-white/[0.06] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F4C86B]">Network registry</p><h3 className="mt-1 text-lg font-medium tracking-tight text-white" data-testid="mandi-table-title">Mandi performance</h3><p className="mt-1 text-xs text-[#8CA0B5]" data-testid="mandi-table-subtitle">Selected crop · per-mandi averages from the cleaned price, arrival and transport rows</p></div><div className="flex items-center gap-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-[#5B738B]" /><Input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search registry" className="h-9 w-full border-white/[0.08] bg-[#07111F]/60 pl-9 text-xs sm:w-44" data-testid="mandi-table-search-input-secondary" /></div></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-white/[0.06] bg-[#07111F]/20"><tr>{COLUMNS.map((column) => <th key={column.label || "actions"} className="px-5 py-3 font-mono text-[9px] uppercase tracking-[0.14em] text-[#5B738B]">{column.key ? <button type="button" onClick={() => toggleSort(column.key as SortKey)} className={`flex items-center gap-1 transition-colors hover:text-white ${sortKey === column.key ? "text-[#A5F36B]" : ""}`} data-testid={`mandi-table-sort-${column.key}`}>{column.label}{sortKey === column.key ? (direction === "asc" ? <ArrowUp className="size-3" /> : <ArrowDown className="size-3" />) : <ArrowUpDown className="size-3 opacity-40" />}</button> : column.label}</th>)}</tr></thead>
    <tbody>{pageRows.map((row) => <tr key={row.mandi_id} onClick={() => onSelectMandi(row.mandi_id)} className={`group cursor-pointer border-b border-white/[0.05] transition-colors hover:bg-white/[0.03] ${selectedMandiId === row.mandi_id ? "bg-[#A5F36B]/[0.05]" : ""}`} data-testid={`mandi-table-row-${row.mandi_id.toLowerCase()}`}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className={`flex size-8 items-center justify-center rounded-lg text-[10px] font-bold ${row.risk === "high" ? "bg-[#FF8585]/10 text-[#FF8585]" : row.risk === "medium" ? "bg-[#F4C86B]/10 text-[#F4C86B]" : "bg-[#A5F36B]/10 text-[#A5F36B]"}`}>{row.mandi_id.replace("MANDI", "M")}</div><div><p className="text-xs font-medium text-white">{row.mandi_name}</p><p className="mt-0.5 font-mono text-[9px] text-[#5B738B]">{row.mandi_id} · {row.district} · {row.mandi_type}</p></div></div></td><td className="px-5 py-4 text-xs text-[#8CA0B5]">{row.state}</td><td className="px-5 py-4"><p className="text-xs font-medium text-white">{formatInr(row.modal_price)}</p><p className="mt-0.5 text-[10px] text-[#F4C86B]">{formatInr(row.msp)} msp{row.price_records === 0 ? " · crop avg" : ""}</p></td><td className={`px-5 py-4 text-xs font-medium ${row.price_gap >= 0 ? "text-[#A5F36B]" : "text-[#FF8585]"}`}>{row.price_gap >= 0 ? "+" : "−"}{formatInr(Math.abs(row.price_gap))}<p className="mt-0.5 text-[9px] font-normal text-[#5B738B]">{row.below_msp_percentage.toFixed(0)}% rows below</p></td><td className="px-5 py-4 text-xs text-[#E2E8F0]">{formatQtl(row.arrival_quantity_qtl)} <span className="text-[10px] text-[#5B738B]">qtl</span></td><td className="px-5 py-4 text-xs text-[#E2E8F0]">{row.transit_hours.toFixed(1)}h<p className="mt-0.5 text-[9px] text-[#5B738B]">{row.destination_warehouse}</p></td><td className="px-5 py-4"><span className="flex items-center gap-1.5 text-[10px] text-[#8CA0B5]"><CloudSun className="size-3 text-[#69C7F5]" />{row.weather}</span></td><td className="px-5 py-4"><span className={`rounded-full border px-2 py-1 font-mono text-[9px] uppercase tracking-wider ${riskStyle[row.risk]}`} data-testid={`mandi-risk-badge-${row.mandi_id.toLowerCase()}`}>{row.risk}</span></td><td className="px-5 py-4"><ExternalLink className="size-3.5 text-[#5B738B] transition-colors group-hover:text-[#A5F36B]" /></td></tr>)}</tbody></table></div>
    {visibleRows.length === 0 && <div className="flex flex-col items-center justify-center gap-2 p-12 text-center" data-testid="mandi-table-empty-state"><ShieldCheck className="size-8 text-[#5B738B]" /><p className="text-sm text-white">No mandis match this filter</p><p className="text-xs text-[#8CA0B5]">Try a different name, state, or reset the control center.</p></div>}
    <div className="flex flex-col gap-3 border-t border-white/[0.06] p-4 sm:flex-row sm:items-center sm:justify-between" data-testid="mandi-table-pagination"><p className="font-mono text-[10px] uppercase tracking-wider text-[#5B738B]" data-testid="mandi-table-row-count">Showing {visibleRows.length ? page * PAGE_SIZE + 1 : 0}–{Math.min(visibleRows.length, (page + 1) * PAGE_SIZE)} of {visibleRows.length} matching · {totalCount} monitored mandis</p><div className="flex items-center gap-2"><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] text-[#8CA0B5] disabled:opacity-40" disabled={page === 0} onClick={() => setPage((current) => Math.max(0, current - 1))} data-testid="mandi-table-previous-button" aria-label="Previous page"><ChevronLeft className="size-4" /></Button><span className="rounded-lg bg-[#A5F36B]/10 px-3 py-1.5 font-mono text-[10px] text-[#A5F36B]" data-testid="mandi-table-page-indicator">{String(page + 1).padStart(2, "0")} / {String(pageCount).padStart(2, "0")}</span><Button variant="ghost" size="icon-sm" className="border border-white/[0.08] text-[#8CA0B5] disabled:opacity-40" disabled={page >= pageCount - 1} onClick={() => setPage((current) => Math.min(pageCount - 1, current + 1))} data-testid="mandi-table-next-button" aria-label="Next page"><ChevronRight className="size-4" /></Button></div></div></section>;
}
